name: Deploy to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    environment: hello-world
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Debug secrets
      run: |
        echo "EC2_HOST: ${{ vars.EC2_HOST }}"
        echo "EC2_USER: ${{ vars.EC2_USER }}"
    
    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.EC2_HOST }}
        username: ${{ vars.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/projects/hola-mundo
          git pull origin master
